name: total_torque_accounting
description: A comprehensive accounting application for Total Torque Express & Spares Hub.
publish_to: 'none'
version: 1.0.0+2

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  pdf: ^3.8.0
  path_provider: ^2.0.15
  shared_preferences: ^2.1.1
  provider: ^6.0.5
  dio: ^5.1.2
  intl: ^0.18.0
  printing: ^5.9.3
  file_picker: ^8.1.7
  url_launcher: ^6.1.11
  open_file: ^3.3.2
  flutter_lints: ^2.0.0
  signature: ^5.4.0
  smooth_page_indicator: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.png
    - assets/images/

  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf